name: Tests

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        config:
          - {os: windows-latest, r: 'release'}
          - {os: windows-latest, r: 'devel', rtools-version: '42'}
    name: R ${{ matrix.config.r }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
          rtools-version: ${{ matrix.config.rtools-version }}
      - run: |
          # check the variables outside R
          echo "R_HOME is $env:R_HOME"
          echo "PATH is $env:PATH"

          # check the command path
          Get-Command R.exe
          
          # check the variables inside R
          Rscript.exe -e "print(normalizePath(R.home()))"
          Rscript.exe -e "print(Sys.getenv('R_HOME'))"
          Rscript.exe -e "print(Sys.getenv('PATH'))"

          # check the structure under R_HOME
          tree C:/R
